# -*- python -*-
Import("env")

env.Program(["Events_1.cc"], LIBS=env.libs["boost"] + ["daf_base"] + ["pex_exceptions"] + ["pex_policy"] + ["pex_logging"] + ["ctrl_events"]) 
env.Program(["Events_2.cc"], LIBS=env.libs["boost"] + ["daf_base"] + ["pex_exceptions"] +  ["pex_policy"] + ["pex_logging"] + ["ctrl_events"]) 
env.Program(["EventSystem_1.cc"], LIBS=env.libs["boost"] + ["daf_base"] + ["pex_exceptions"] +["pex_policy"] + ["pex_logging"] + ["ctrl_events"]) 
env.Program(["EventSystem_2.cc"], LIBS=env.libs["boost"] + ["daf_base"] + ["pex_exceptions"] +["pex_policy"] + ["pex_logging"] + ["ctrl_events"]) 

#
# Tests
#
import lsst.tests
import os
env['ENV']['SEAL_PLUGINS'] = os.environ['SEAL_PLUGINS']

tests = lsst.tests.Control(env, verbose=True)

tests.run("Events_1.cc")
tests.run("Events_2.cc")
tests.run("Events_3.py")
tests.run("Events_4.py")
tests.run("Events_5.py")
tests.run("Events_6.py")
tests.run("Events_7.py")
tests.run("EventSystem_1.cc")
tests.run("EventSystem_2.cc")
tests.run("EventSystem_3.py")
tests.run("EventSystem_4.py")
tests.run("EventSystem_5.py")
tests.run("EventSystem_6.py")
tests.run("EventSystem_7.py")
tests.run("EventLogging_1.py")
