# -*- python -*-
Import("env")

env.CheckSwig("python", ilang="c++", includedProducts="utils daf_base pex_policy pex_exceptions pex_logging")
#env.LoadableModuleIncomplete("_data", Split("data.i"), LIBS=env.libs["boost"] + ["mwi"])
#env.LoadableModuleIncomplete("_utils", Split("utils.i"), LIBS=env.libs["boost"] + ["mwi"])
#env.LoadableModuleIncomplete("_logging", Split("logging.i"), LIBS=env.libs["boost"] + ["mwi"])
env.LoadableModuleIncomplete("_events", Split("events.i"), LIBS=env.libs["activemqcpp"] + ["boost"] + ["daf_base"] + ["pex_policy"] + ["pex_exceptions"] + ["pex_logging"] + ["ctrl_events"])
