# -*- python -*-
from lsst.sconsUtils import env, targets

targets["python"] = env.SwigLoadableModule(
    "_eventsLib", "eventsLib.i",
    LIBS=env.getLibs("main python"),
    SWIGFLAGS=env["SWIGFLAGS"] + ["-threads"]
    )

