# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.31
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _events
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


import lsst.mwi.data
import lsst.mwi.policy

class PySwigIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, PySwigIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, PySwigIterator, name)
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    __swig_destroy__ = _events.delete_PySwigIterator
    __del__ = lambda self : None;
    def value(*args): return _events.PySwigIterator_value(*args)
    def incr(*args): return _events.PySwigIterator_incr(*args)
    def decr(*args): return _events.PySwigIterator_decr(*args)
    def distance(*args): return _events.PySwigIterator_distance(*args)
    def equal(*args): return _events.PySwigIterator_equal(*args)
    def copy(*args): return _events.PySwigIterator_copy(*args)
    def next(*args): return _events.PySwigIterator_next(*args)
    def previous(*args): return _events.PySwigIterator_previous(*args)
    def advance(*args): return _events.PySwigIterator_advance(*args)
    def __eq__(*args): return _events.PySwigIterator___eq__(*args)
    def __ne__(*args): return _events.PySwigIterator___ne__(*args)
    def __iadd__(*args): return _events.PySwigIterator___iadd__(*args)
    def __isub__(*args): return _events.PySwigIterator___isub__(*args)
    def __add__(*args): return _events.PySwigIterator___add__(*args)
    def __sub__(*args): return _events.PySwigIterator___sub__(*args)
    def __iter__(self): return self
PySwigIterator_swigregister = _events.PySwigIterator_swigregister
PySwigIterator_swigregister(PySwigIterator)

class ios_base(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, ios_base, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, ios_base, name)
    def __init__(self): raise AttributeError, "No constructor defined"
    __repr__ = _swig_repr
    erase_event = _events.ios_base_erase_event
    imbue_event = _events.ios_base_imbue_event
    copyfmt_event = _events.ios_base_copyfmt_event
    def register_callback(*args): return _events.ios_base_register_callback(*args)
    def flags(*args): return _events.ios_base_flags(*args)
    def setf(*args): return _events.ios_base_setf(*args)
    def unsetf(*args): return _events.ios_base_unsetf(*args)
    def precision(*args): return _events.ios_base_precision(*args)
    def width(*args): return _events.ios_base_width(*args)
    __swig_getmethods__["sync_with_stdio"] = lambda x: _events.ios_base_sync_with_stdio
    if _newclass:sync_with_stdio = staticmethod(_events.ios_base_sync_with_stdio)
    def imbue(*args): return _events.ios_base_imbue(*args)
    def getloc(*args): return _events.ios_base_getloc(*args)
    __swig_getmethods__["xalloc"] = lambda x: _events.ios_base_xalloc
    if _newclass:xalloc = staticmethod(_events.ios_base_xalloc)
    def iword(*args): return _events.ios_base_iword(*args)
    def pword(*args): return _events.ios_base_pword(*args)
    __swig_destroy__ = _events.delete_ios_base
    __del__ = lambda self : None;
ios_base_swigregister = _events.ios_base_swigregister
ios_base_swigregister(ios_base)
cvar = _events.cvar
ios_base.boolalpha = _events.cvar.ios_base_boolalpha
ios_base.dec = _events.cvar.ios_base_dec
ios_base.fixed = _events.cvar.ios_base_fixed
ios_base.hex = _events.cvar.ios_base_hex
ios_base.internal = _events.cvar.ios_base_internal
ios_base.left = _events.cvar.ios_base_left
ios_base.oct = _events.cvar.ios_base_oct
ios_base.right = _events.cvar.ios_base_right
ios_base.scientific = _events.cvar.ios_base_scientific
ios_base.showbase = _events.cvar.ios_base_showbase
ios_base.showpoint = _events.cvar.ios_base_showpoint
ios_base.showpos = _events.cvar.ios_base_showpos
ios_base.skipws = _events.cvar.ios_base_skipws
ios_base.unitbuf = _events.cvar.ios_base_unitbuf
ios_base.uppercase = _events.cvar.ios_base_uppercase
ios_base.adjustfield = _events.cvar.ios_base_adjustfield
ios_base.basefield = _events.cvar.ios_base_basefield
ios_base.floatfield = _events.cvar.ios_base_floatfield
ios_base.badbit = _events.cvar.ios_base_badbit
ios_base.eofbit = _events.cvar.ios_base_eofbit
ios_base.failbit = _events.cvar.ios_base_failbit
ios_base.goodbit = _events.cvar.ios_base_goodbit
ios_base.app = _events.cvar.ios_base_app
ios_base.ate = _events.cvar.ios_base_ate
ios_base.binary = _events.cvar.ios_base_binary
ios_base.ios_base_in = _events.cvar.ios_base_ios_base_in
ios_base.out = _events.cvar.ios_base_out
ios_base.trunc = _events.cvar.ios_base_trunc
ios_base.beg = _events.cvar.ios_base_beg
ios_base.cur = _events.cvar.ios_base_cur
ios_base.end = _events.cvar.ios_base_end
ios_base_sync_with_stdio = _events.ios_base_sync_with_stdio
ios_base_xalloc = _events.ios_base_xalloc

class ios(ios_base):
    __swig_setmethods__ = {}
    for _s in [ios_base]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, ios, name, value)
    __swig_getmethods__ = {}
    for _s in [ios_base]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ios, name)
    __repr__ = _swig_repr
    def rdstate(*args): return _events.ios_rdstate(*args)
    def clear(*args): return _events.ios_clear(*args)
    def setstate(*args): return _events.ios_setstate(*args)
    def good(*args): return _events.ios_good(*args)
    def eof(*args): return _events.ios_eof(*args)
    def fail(*args): return _events.ios_fail(*args)
    def bad(*args): return _events.ios_bad(*args)
    def exceptions(*args): return _events.ios_exceptions(*args)
    def __init__(self, *args): 
        this = _events.new_ios(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_ios
    __del__ = lambda self : None;
    def tie(*args): return _events.ios_tie(*args)
    def rdbuf(*args): return _events.ios_rdbuf(*args)
    def copyfmt(*args): return _events.ios_copyfmt(*args)
    def fill(*args): return _events.ios_fill(*args)
    def imbue(*args): return _events.ios_imbue(*args)
    def narrow(*args): return _events.ios_narrow(*args)
    def widen(*args): return _events.ios_widen(*args)
ios_swigregister = _events.ios_swigregister
ios_swigregister(ios)

class ostream(ios):
    __swig_setmethods__ = {}
    for _s in [ios]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, ostream, name, value)
    __swig_getmethods__ = {}
    for _s in [ios]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, ostream, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_ostream(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_ostream
    __del__ = lambda self : None;
    def __lshift__(*args): return _events.ostream___lshift__(*args)
    def put(*args): return _events.ostream_put(*args)
    def write(*args): return _events.ostream_write(*args)
    def flush(*args): return _events.ostream_flush(*args)
    def tellp(*args): return _events.ostream_tellp(*args)
    def seekp(*args): return _events.ostream_seekp(*args)
ostream_swigregister = _events.ostream_swigregister
ostream_swigregister(ostream)
cin = cvar.cin
cout = cvar.cout
cerr = cvar.cerr
clog = cvar.clog

class istream(ios):
    __swig_setmethods__ = {}
    for _s in [ios]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, istream, name, value)
    __swig_getmethods__ = {}
    for _s in [ios]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, istream, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_istream(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_istream
    __del__ = lambda self : None;
    def __rshift__(*args): return _events.istream___rshift__(*args)
    def gcount(*args): return _events.istream_gcount(*args)
    def get(*args): return _events.istream_get(*args)
    def getline(*args): return _events.istream_getline(*args)
    def ignore(*args): return _events.istream_ignore(*args)
    def peek(*args): return _events.istream_peek(*args)
    def read(*args): return _events.istream_read(*args)
    def readsome(*args): return _events.istream_readsome(*args)
    def putback(*args): return _events.istream_putback(*args)
    def unget(*args): return _events.istream_unget(*args)
    def sync(*args): return _events.istream_sync(*args)
    def tellg(*args): return _events.istream_tellg(*args)
    def seekg(*args): return _events.istream_seekg(*args)
istream_swigregister = _events.istream_swigregister
istream_swigregister(istream)

class iostream(istream,ostream):
    __swig_setmethods__ = {}
    for _s in [istream,ostream]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, iostream, name, value)
    __swig_getmethods__ = {}
    for _s in [istream,ostream]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, iostream, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_iostream(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_iostream
    __del__ = lambda self : None;
iostream_swigregister = _events.iostream_swigregister
iostream_swigregister(iostream)

endl_cb_ptr = _events.endl_cb_ptr
endl = _events.endl
ends_cb_ptr = _events.ends_cb_ptr
ends = _events.ends
flush_cb_ptr = _events.flush_cb_ptr
flush = _events.flush
class floatArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, floatArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_floatArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_floatArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _events.floatArray___getitem__(*args)
    def __setitem__(*args): return _events.floatArray___setitem__(*args)
    def cast(*args): return _events.floatArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _events.floatArray_frompointer
    if _newclass:frompointer = staticmethod(_events.floatArray_frompointer)
floatArray_swigregister = _events.floatArray_swigregister
floatArray_swigregister(floatArray)
floatArray_frompointer = _events.floatArray_frompointer

class doubleArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, doubleArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, doubleArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_doubleArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_doubleArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _events.doubleArray___getitem__(*args)
    def __setitem__(*args): return _events.doubleArray___setitem__(*args)
    def cast(*args): return _events.doubleArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _events.doubleArray_frompointer
    if _newclass:frompointer = staticmethod(_events.doubleArray_frompointer)
doubleArray_swigregister = _events.doubleArray_swigregister
doubleArray_swigregister(doubleArray)
doubleArray_frompointer = _events.doubleArray_frompointer

LSST_UTILS_H = _events.LSST_UTILS_H
guessSvnVersion = _events.guessSvnVersion
stringToAny = _events.stringToAny
class EventReceiver(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, EventReceiver, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EventReceiver, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_EventReceiver(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_EventReceiver
    __del__ = lambda self : None;
    def receive(*args): return _events.EventReceiver_receive(*args)
    infiniteTimeout = _events.EventReceiver_infiniteTimeout
EventReceiver_swigregister = _events.EventReceiver_swigregister
EventReceiver_swigregister(EventReceiver)

class EventTransmitter(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr_nondynamic(self, EventTransmitter, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, EventTransmitter, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _events.new_EventTransmitter(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _events.delete_EventTransmitter
    __del__ = lambda self : None;
    def publish(*args): return _events.EventTransmitter_publish(*args)
EventTransmitter_swigregister = _events.EventTransmitter_swigregister
EventTransmitter_swigregister(EventTransmitter)



