# -*- python -*-
Import('env')

env.SharedLibrary('ctrl_events', map(lambda str: "../src/" + str,
                            ["EventTransmitter.cc",
                             "EventReceiver.cc",
                             "EventFormatter.cc",
                             "EventLog.cc",
                             "EventSystem.cc",
                             "EventLibrary.cc",
                             "Event.cc",
                             ]), LIBS=env.getlibs("boost pex_policy pex_exceptions pex_logging daf_base utils activemqcpp") )
