# -*- python -*-
Import('env')

env.SharedLibrary('ctrl_events', map(lambda str: "../src/" + str,
                            [
                             "EventTypes.cc",
                             "Event.cc",
                             "StatusEvent.cc",
                             "CommandEvent.cc",
                             "LogEvent.cc",
                             "PipelineLogEvent.cc",
                             "EventTransmitter.cc",
                             "EventReceiver.cc",
                             "EventFormatter.cc",
                             "EventLog.cc",
                             "EventSystem.cc",
                             "EventLibrary.cc",
                             "EventFactory.cc",
                             ]), LIBS=env.getlibs("boost pex_policy pex_exceptions pex_logging daf_base utils activemqcpp") )
